#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

PACKAGES="$(go list ./... | grep -Ev '(vendor|e2e)')"

[ "${ARCH}" == "amd64" ] && RACE=-race
go test ${RACE} -cover -tags=test ${PACKAGES}
